Update cf.yml

diff --git a/.github/workflows/cf.yml b/.github/workflows/cf.yml
--- a/.github/workflows/cf.yml
+++ b/.github/workflows/cf.yml
@@ -2,6 +2,7 @@ name: cf workers
 
 on:
   workflow_dispatch:
+
   push:
     branches:
       - master
@@ -15,12 +16,11 @@ jobs:
     environment: cf
     steps:
       - uses: actions/checkout@v4
-      
+
       - name: Setup Rust
-        uses: actions-rust-lang/setup-rust-toolchain@v1
+        uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
-          components: rust-src
 
       - name: Install wasm-bindgen-cli
         run: cargo install -f wasm-bindgen-cli --version 0.2.100
@@ -28,7 +28,23 @@ jobs:
       - name: Install worker-build
         run: cargo install -q worker-build
 
-      - name: deploy
+      - name: Poison the cache
+        run: |
+          # Run a build that is expected to fail to populate the cache
+          worker-build --release || true
+          # Find the incorrect wasm-bindgen binary in the cache
+          WASM_BINDGEN_CACHE_PATH=$(find ~/.cache/worker-build -type f -name "wasm-bindgen")
+          echo "Found wasm-bindgen at: $WASM_BINDGEN_CACHE_PATH"
+          # Overwrite the incorrect cached binary with the correct one
+          cp "$(which wasm-bindgen)" "$WASM_BINDGEN_CACHE_PATH"
+
+      - name: Build
+        run: worker-build --release
+
+      - name: Remove build command from wrangler.toml
+        run: sed -i '/^\[build\]$/,/^command/d' wrangler.toml
+
+      - name: Deploy
         uses: cloudflare/wrangler-action@v3
         with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
